apiVersion: v1
kind: Pod
metadata:
  name: redis-server
  labels:
    app: redis
spec:
  containers:
  - name: redis
    image: redis:5.0.4
    command:
      - redis-server
    ports:
    - containerPort: 6379